### ISSUE TITLE
Consumable Items are not consumed.

### ISSUE THREAD

**Issue by Maesejesus** [LeonarthCG/FFTA_Engine_Hacks#11]
First of all, I hope you're doing well, and I apologize for bothering you again so long after you fixed the crash with the item menu.

I wanted to inform that, while surely it doesn't seem to crash, for some reason after patching with your tools consumable items are not consumed. I have tested my own changes separately and with a clean, verified ROM only patched with your Engine Hacks.

**Comment by LeonarthCG** [comment]
Thanks for letting me know! I pushed a new change to fix this issue, I'll leave this open in case it doesn't work right, it is quite a hacky fix.

I'm certain this worked at some point, because I had even tested this with the percentage chance for items to break.
For example, you can add an item ability that uses a rod to cast fire but breaks the rod 25% of the time, and I did have videos of this in action.
I'm not sure when this stopped working and I honestly don't have the time to figure the details out, so dirty fix it is.

**Comment by Maesejesus** [comment]
Sorry for not answering before, I didn't have the time to try it.

I used the version with the latest changes and consumable items work again. Thank you so much, Leonarth!

**Comment by Maesejesus** [comment]
Sorry for not answering before, I didn't have the time to try it.

I used the version with the latest changes and consumable items work again. Thank you so much, Leonarth!
