### ISSUE TITLE
JP Reset after mission

### ISSUE THREAD

**Issue by thespbgamer** [LeonarthCG/FFTA_Engine_Hacks#2]
**Error description:** After completing the mission if the **_"EXP?"_** and **_"Judge PTS"_** are turned **Off**, the JP in certain characters reset, gaining only the JP in the missions rewards. Meaning, if you have 268 JP in the character and the missions gives you 50JP, in the end of the missions, you only have a total of 50JP, losing the 268JP you previously had.

**Options I picked:** Default Options + stealShoes

**ROM Used:** Clean USA ROM

**Comment by LeonarthCG** [comment]
First of all, I want to say I have never used those options and would 100% not have considered checking them if it weren't for this issue, so thank you for that.

I have been unable to replicate this issue as described.
However, I have been able to replicate something similar, which I suspect is the real nature of the issue and had actually been reported to me in the past, but I could never replicate before.

When "Judge PTS?" is Off (this was the key part I was missing before, thanks again), getting rewarded by a judge makes sure your JP is capped at 10, just like vanilla. This was increased to 9999 in other parts of the code, I just didn't know about this one place. The result of this is that any unit that is rewarded by a judge will get their JP set to 10 almost all of the time, so their JP ends up being 10 plus the mission reward after the mission is complete.

This issue should now have been fixed by this commit: https://github.com/LeonarthCG/FFTA_Engine_Hacks/commit/6c3d5f2e8b56381c59eaea0b1f4832ff28c3096b
Feel free to open a new issue if you think this is not it and definitely open a new issue if your JP still resets.
