### ISSUE TITLE
Equipment list menu closes immediately when trying to change equipment

### ISSUE THREAD

**Issue by kidyudiqy** [LeonarthCG/FFTA_Engine_Hacks#6]
- **Steps to reproduce:** Make a hack using the configuration from the latest master branch (a0df5d9)
- **Expected result:** You can change equipment.
![working-equip-list](https://user-images.githubusercontent.com/23061713/118395003-44b26100-b672-11eb-9a9d-641d2e578af4.gif)
- **Actual result:** Equipment list menu closes immediately.
![broken-equip-list](https://user-images.githubusercontent.com/23061713/118394918-cf469080-b671-11eb-8653-48b615aab430.gif)
- **Workarounds:** Commenting out this line avoids the problem, but this disables the new inventory system entirely.
https://github.com/LeonarthCG/FFTA_Engine_Hacks/blob/a0df5d93e1f16c0f56b5f840c6cb6421028b68b0/Engine%20Hacks/_MasterHackInstaller.event#L349

**Comment by LeonarthCG** [comment]
Sorry for taking so long to respond.

The menu not opening is not a bug at all, and is in fact vanilla behaviour. This is exactly what happens in vanilla when the item list is empty. Even though you own items, the list is empty because of how the new inventory works.

The difference between vanilla and the new inventory is that the engine hacks have an option to not list items that are not available to equip, this includes both items the unit simply can't equip and items which you have no free copies of. You can change this back by uncommenting the definition for "listUselessEntries" in "\Engine Hacks\newInventory\options.event".

Hope this cleared up the confusion. There's a few configuration files like this one that can be found in their respective folders, the reason being that I like to think of this repository as a collection of individual (sometimes intertwining) engine hacks.

**Comment by kidyudiqy** [comment]
Ah, so that's how it should've worked... Thanks for the explanation.
